using System.IO;

namespace Geckon.Octopus.Plugins.Transcoding.Carbon
{
	internal static class CarbonQueryTranscodeVideo
	{
		public static string CompileVideoEncodeJobXml(string carbonPresetGUID, string sourceFilePath, string destinationFilePath, CarbonVideoInformation videoInformation)
		{
			return
				"<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
				"<cnpsXML>" +
				"   <Sources>" +
				"       <Module_0 Filename=\"" + sourceFilePath + "\" />" +
				"   </Sources>" +
				"	<Destinations>" +
				"		<Module_0 PresetGUID=\"{" + carbonPresetGUID + "}\">" +
				"			<ModuleData " +
				"				CML_P_BaseFileName=\"" + Path.GetFileName(destinationFilePath) + "\"" +
				"				CML_P_Path=\"" + Path.GetDirectoryName(destinationFilePath) + "\" " +
				"				CML_P_ForcedSplitMinutes.DWD=\"0\" " +
				"				CML_P_SourceSegmentSel.DWD=\"0\" " +
				"				CML_P_SourceSegmentStart.DWD=\"-1\" " +
				"				CML_P_SourceSegmentTime.DWD=\"-1\" " +
				"				CML_P_SourceSegmentStartDbl.DBL=\"0.000000\" " +
				"				CML_P_SourceSegmentTimeDbl.DBL=\"0.000000\" " +
				"				CML_P_SplitSelection.DWD=\"0\" " +
				"				CML_P_SplitTime.DWD=\"10\" " +
				"				CML_V_SizeX.DWD=\"" + videoInformation.Width + "\" " +
				"				CML_V_SizeY.DWD =\"" + videoInformation.Height + "\" " +
				"				DestFileUseSource.DWD=\"1\" " +
				"				number_of_passes.DWD=\"1\" " +
				"				bitrate.DWD=\"" + videoInformation.VideoBitRate + "\"" +
				"				audio_bitrate.DWD =\"" + videoInformation.AudioBitRate + "\" " +
				"				ExportDescription.BIN=\"dGlwczRncG1scHBhMIAJAA0CAQA=\" " +
				"				UseSourceDuration.DWD=\"0\" " +
				"				ExportSetting.BIN=\"2wQAAHRpcHM0Z3BtbHBwYTCACQANAgEAAAAAAAAAAAAAAAAAAAAEz3NlYW4AAAABAAAAFQAAAAAAAAGedmlkZQAAAAEAAAAPAAAAAAAAACJzcHRsAAAAAQAAAAAAAAAAYXZjMQAAAAAAIAAAAwAAAAAgdHBybAAAAAEAAAAAAAAAAAAAAwAAGQAAAAAAAAAAACRkcmF0AAAAAQAAAAAAAAAAAAW42AAAAAAAAAMAAAADAAAAABVtcHNvAAAAAQAAAAAAAAAAAAAAABhtZnJhAAAAAQAAAAAAAAAAAAAAAAAAABhwc2ZyAAAAAQAAAAAAAAAAAAAAAAAAABViZnJhAAAAAQAAAAAAAAAAAAAAABZtcGVzAAAAAQAAAAAAAAAAAQAAAAAoaGFyZAAAAAEAAAAAAAAAAAAAAAAAGsd4QEAAAAAAAAAAAAAAAAAAFmVuZHMAAAABAAAAAAAAAAAAAAAAABZjZmxnAAAAAQAAAAAAAAAAAEQAAAAUY2x1dAAAAAEAAAAAAAAAAAAAABx2ZXJzAAAAAQAAAAAAAAAAAAMAGgABAAAAAAAYd2R0aAAAAAEAAAAAAAAAAAMAAAAAAAAYaGVndAAAAAEAAAAAAAAAAAJAAAAAAABcaXNpegAAAAEAAAADAAAAAAAAABhpd2R0AAAAAQAAAAAAAAAAAAADAAAAABhpaGd0AAAAAQAAAAAAAAAAAAACQAAAABhzY2FtAAAAAQAAAAAAAAAAdHJpbQAAARNzb3VuAAAAAQAAAAYAAAAAAAAAGHNzY3QAAAABAAAAAAAAAABtcDRhAAAAGHNzcnQAAAABAAAAAAAAAACsRAAAAAAAFnNzc3MAAAABAAAAAAAAAAAAEAAAABZzc2NjAAAAAQAAAAAAAAAAAAIAAACHY2RlYwAAAAEAAAAAAAAAAAAAAAxmcm1hbXA0YQAAAAxtcDRhAAAAAAAAADNlc2RzAAAAAAOAgIAiAAAABICAgBRAFQAYAAADawAAA2sABYCAgAISEAaAgIABAgAAAAxzcmNxYAAAAAAAAAxhY2JmAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAcdmVycwAAAAEAAAAAAAAAAAADABMAAQAAAAAAGGZ0eXAAAAABAAAAAAAAAABtcDQyAAAAGGVudmkAAAABAAAAAAAAAABoMjY0AAAAGGVuc28AAAABAAAAAAAAAABhYWMgAAAAGGNvbmYAAAABAAAAAAAAAABtcGc0AAAAGGFyYXQAAAABAAAAAAAAAAAAAADgAAAAGGNoYW4AAAABAAAAAAAAAAAAAAACAAAAGGFzcnQAAAABAAAAAAAAAACsRAAAAAAAGGFxbHQAAAABAAAAAAAAAAAAAABgAAAAGGJhc2UAAAABAAAAAAAAAAAAAAEAAAAAGHR4ZW4AAAABAAAAAAAAAAAAAAACAAAAFnJ0eHQAAAABAAAAAAAAAAAAAAAAABhoaW50AAAAAQAAAAAAAAAAAAAAAQAAABhwc2l6AAAAAQAAAAAAAAAAAAAFqgAAABhwZHVyAAAAAQAAAAAAAAAAAAAAZAAAABhyc21rAAAAAQAAAAAAAAAAAAAAAQAAABhiZnJtAAAAAQAAAAAAAAAAAAAAAAAAABhwcm9mAAAAAQAAAAAAAAAAAAAAAQAAABh2cmFpAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\" " +
				"				FrameMode.DWD=\"0\" " +
				"				AspectRatio.BIN=\"AQAAAAEAAAA=\" " +
				"				PixelAspect_X.DWD=\"1\" " +
				"				PixelAspect_Y.DWD=\"1\" " +
				"				CreatorMachine=\"CARBON-MASTER\" " +
				"				CreatorUser=\"DRadmin\" " +
				"			/>" +
				"			<Filter_0/>" +
				"			<Filter_1/>" +
				"		</Module_0>" +
				"	</Destinations>" +
				"</cnpsXML>";
		}
	}
}