//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geckon.Octopus.Controller.Service.Test.ControllerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControllerService.IControllerService")]
    public interface IControllerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControllerService/GetSession", ReplyAction="http://tempuri.org/IControllerService/GetSessionResponse")]
        string GetSession(int clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControllerService/AddJob", ReplyAction="http://tempuri.org/IControllerService/AddJobResponse")]
        void AddJob(string jobXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControllerService/GetJobByID", ReplyAction="http://tempuri.org/IControllerService/GetJobByIDResponse")]
        string GetJobByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControllerService/GetJobs", ReplyAction="http://tempuri.org/IControllerService/GetJobsResponse")]
        string GetJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControllerService/GetJobByStatus", ReplyAction="http://tempuri.org/IControllerService/GetJobByStatusResponse")]
        string GetJobByStatus(int status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControllerServiceChannel : Geckon.Octopus.Controller.Service.Test.ControllerService.IControllerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControllerServiceClient : System.ServiceModel.ClientBase<Geckon.Octopus.Controller.Service.Test.ControllerService.IControllerService>, Geckon.Octopus.Controller.Service.Test.ControllerService.IControllerService {
        
        public ControllerServiceClient() {
        }
        
        public ControllerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControllerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSession(int clientID) {
            return base.Channel.GetSession(clientID);
        }
        
        public void AddJob(string jobXml) {
            base.Channel.AddJob(jobXml);
        }
        
        public string GetJobByID(int id) {
            return base.Channel.GetJobByID(id);
        }
        
        public string GetJobs() {
            return base.Channel.GetJobs();
        }
        
        public string GetJobByStatus(int status) {
            return base.Channel.GetJobByStatus(status);
        }
    }
}
